{ +block{enhancedstats} }
-coremetrics-
-CoreMetrics\.
-elqImg\.
-flash-cookies/
-omniture-
-omniture\.js
-OmnitureSWF\.
-s_code\.
-sitecatalyst\.
-webtrends-
-Webtrends\.
-webtrends_
\.cmdatatagutils\.
\.com/ga\..*\.js
\.com/ga\.js
\.com/mt\.js
\.eluminate\.
\.event-tracking\.js
\.hbx\.js\?
\.omniture\.
\.omniture_
\.php\?referer=
\.s_code\.js
\.s_code_
\.siteCatalyst\.
\.siteCatalystTL\.
\.slimsurveys\.
\.tealium\.
\.Webtrends\.js
/_omniture/.*
/_tl_track\.js
/abpTest/.*
/adobe-dtm-
/Adobe-DTM/.*
/ajax/hit/.*
/akqa\.tracking\.
/analytics/.*/xtcore\.js
/analytics/mbox_
/at\.js\.php$
/atm_code\.js
/audiencemeasurement\.
/bidiqCookieDropper\.
/boomerang-0.*\.js
/catalyst\.js
/cllc\.tracking\.js
/cm_controldata\.
/cmdatagutils\.
/cmdatatagutils\.
/cmdatatagutils_
/cmEluminate\.
/cmtaggingservices\.
/ComScorePeopleCom\.
/cookie-id\.js\?
/coremetrics-
/coremetrics\.
/coremetrics/.*
/CoreMetricsSupportLib/.*
/CoreMetricsTracking\.
/customOmnitureData\.js
/dcs_head\.js
/dcs_tag\.js
/dcs_tag1\.js
/dcs_tag2\.js
/dcs_tag_
/dcstag_
/ecomfw\.min\.js
/elq_tracking-
/elqCPers\.
/elqFCS\.
/eluminate\.
/eluminate_
/figp\.js
/foresee-
/foresee/.*
/foreseeforesee-
/forsee-
/foxomniture\.swf
/FoxOmnitureMonitor\.
/fp\.min\.jsp
/fp2\.js
/gaManager\.js
/gamepageomniture\.
/gannettomniture\.swf
/gapro-1\.swf
/gatag_v2\.
/global_analytics\.
/global_tracking\.js
/gs-analytics\.
/h-code-
/h-code\.js
/h_code\.
/h_code_
/hbx-load\.html
/hbx\.js
/hbx/hbx_
/hbx2\.js
/hbx_custom\.
/hbx_page_code_
/hbxfunctions\.js
/hbxmedia\.
/hbxmodify\.
/hbxscript\.
/hbxvariables\.
/hitbox/hbx_
/includes/s_code
/iv_nv_footer\.
/iv_nv_header\.
/javascript/hbx_
/javascript/tracking\.js
/javascript/webtrends
/jquery\.dfp\.gpt\.
/jquery\.truste-consent-
/js/analytics/.*
/js/catalyst_ru\.js
/js/hbx-
/js/hbx_.*\.js
/js/mbox-
/js/mbox_
/js/omn/.*
/js/omni_
/js/tracking\.js
/kenshoo\.js
/llbmetrics\.
/loadingpageomniture\.
/logomnitureevent\.js
/mbox\.01\.
/mbox\.20\.
/mbox\.js
/mbox\.orig\.js
/mbox39\.
/mbox_09\.
/mbox_rc\.
/mbox_v1_
/metricspar_
/mod_pagespeed_beacon\?
/NBCUComScore\.
/NBCUOmnitureTracking\.
/omn_global_
/omni_config\.
/omni_footer_
/omni_functions\.js
/omni_mdt\.js
/omni_mediatrack_
/omniHelper\.
/omniSearch_
/omnitrack\.js
/omnitracking\.
/omniture-
/omniture\.
/omniture/.*
/omniture2\.
/omniture\?
/omniture_
/omnitureactionsource\.
/omnitureAnalyticsImpl\.
/OmnitureAppMeasurementExtension\.
/omnitureBase\.
/omniturebodyhcode\.
/omnitureCode\.
/omnitureCompat\.
/omnitureConfig\.
/omnitureconfig/.*
/omniturecore\.js
/omnitureEvents\.
/omnitureEventSink\.
/omnitureFix\.
/OmnitureHandler\.
/OmnitureHelper\.
/OmnitureJavascriptHandler\.
/OmnitureJS\.
/omniturejs/.*
/OmnitureLibrary\.
/omnituremedia\.swf
/OmniturePageCode\.
/omniturePlugin\.
/omniturePlugin_
/omniturerefresh\.
/OmnitureScript\.
/omnitureService\.
/OmnitureSWF-
/OmnitureTrackerAS3\.
/omnituretracking/.*
/omnituretrackingjs/.*
/omnitureZoneTracker\.
/omniunih_
/OmniUserObjAndHelper\.
/omtr_code\.
/omtr_code_
/omtr_tc\.js
/ote/ote\.js
/ote/ste\.js
/page-addviews\?
/pageLevelOmniture\.
/pagespeed\.js
/ParseOmniture\.
/PluginEndPlayOmniture_
/pubsys\.js
/reporting\.do\?
/resonance\.js
/s-code-
/s-code\.js
/s2_code\.
/s_am_code\.
/s_code-
/s_code\.
/s_code/.*
/s_code1\.
/s_code2\.
/s_code3\.
/s_code_
/s_codefullsol\.
/s_codeFULLTTO\.
/s_codeH\.
/s_codeMaps\.
/s_codeV2\.
/s_config_
/s_crainsc\.js
/s_dr_code_
/s_h_code\.
/s_i_code\.
/s_local_customization\.
/s_nd_code\.js
/s_nd_code_
/s_one_code\.
/s_prod_code\.
/s_remote_code\.
/s_remote_code_
/s_site_catalyst\.
/s_tan_code\.
/s_wpn_code\.
/sc_code_
/scode-
/scode\.js
/scode_
/scripts/hbx_
/scripts/mbox\.
/sctl\.js\?
/sdc\.js
/sdc_include_
/sdcTrackingCode\.
/shc_code\.js
/sikomniture_
/site-catalyst\.
/site_catalyst\.
/site_catalyst/.*
/site_catalyst_
/site_specific_code\.
/sitecatalyst-http-
/sitecatalyst\.
/sitecatalyst/.*
/sitecatalyst_
/SiteCatalystAnalytics\.
/SiteCatalystCode_
/SiteCatalystEventListener\.
/sitecatalystfooter\.
/sitecatalysth\.js
/SiteCatalystH243\.
/SiteCatalystInclude\.
/sitecatalystlib\.js
/siteClarity/.*
/sitewise_cms\.
/smartbanner/appbanner\.js
/smeadvert-
/somni\.js
/sonyOmnitureTracker\.
/survey_jspage\.
/tagging-akqa\.
/tan_code\.js
/tealium/.*
/thcn_code\.js
/thcn_code_
/touch-clarity\.
/TouchClarity\.
/touchclarity/.*
/tracking/hbx-
/urchin\.js
/urchin_util\.
/v60\.js
/vs_code\.js
/wa_code\.
/wa_process\.js
/wanalytics-
/web_trends_
/webtrack_tag_
/webtrends-
/webtrends\.
/webtrends1\.
/webtrends2\.
/webtrends3\.
/webtrends75_
/webtrends8_
/webtrends_
/webtrendsAP_
/webtrendsasync\.
/webtrendsasyncloader\.
/webtrendsdt\.
/webtrendsExt\.
/WebTrendsJS/.*
/WebtrendsPlugin\.
/WebTrendsRedirector\.
/webtrendsTag\.
/webtrendsTrack\.
/webtrendsUS\.
/WidgetOmniture\.
/wmgbeaconcode\.
/wmps_tracker\.
/wt-tag\.
/wt_capi\.js
/wt_capi_
/wt_plugins\.
/wt_tag\.js
/wt_tracking\.
/wtbase\.
/wtbase2\.js
/wtbrand\.js
/wtcollect\.
/wtCore\.js
/WTdcsCollect\.js
/WTFarmersSite\.js
/wtfindingmethod\.
/wtid\.js
/wtrack/\?
/wx-metrics\.js
=s_code\.js
=s_code_
=webtrends\.
\?referer.*http=
\?referrer.*http=
_chl_code\.
_CoreMetrics/
_hbx_ad_refresh
_hbx_proxy\.
_hcode\.js
_hightraffic_code\.js
_omnireport\.
_Omniture_
_omnitureVarsComm\.
_s-code\.
_s_code-
_s_code\.
_s_code_
_s_remote_code\.
_scode\.js
_sdc\.js
_sdcTrackingCode\.
_SiteCatalyst\.
_sitecatalyst_
_urchin\.js
_WebTrends\.js
_webtrends/
_webtrends_
_wtBase\.js
_wtbaseV2\.
_wtInit\.js
/cdn-cgi/pe/bag2\?.*atrk\.js
/cdn-cgi/pe/bag2\?.*pagead2\.googlesyndication\.com
/article-countdown-nag\.js
/ep-paywall-portlet/.*
/paywall\.min\.js

.53\.com/resources/js/wt\.js
.aarp\.net/etc/aarp/statics/global/js/mbox\.
.addthis\.com/static/r07/core130\.js
.adziff\.com/mostclicked/
.akamai\.net/.*/includes/iv_footer\.js
.akamai\.net/.*/includes/iv_header\.js
.akamai\.net/cache\.lego\.com/Stats/
.amazonaws\.com/af-bdaz/bquery\.js
.bankofamerica\.com/www/global/js/tc_logging\.js
.bjs\.com[/&:?=_].*_landing\.js
.bosch\.com/WTg/WTg\.js
.bt\.com/media/js/SiteCatalyst-
.burberry\.com[/&:?=_].*/webtrendsMC\.js
.carpartswholesale\.com/includes/cpw_s_code.*\.js
.cbc\.ca/g/stats/linktracker\.js
.cbc\.ca/includes/stats/hbx_
.ccom-cdn\.com/assets/js/ga\.js
.cdc\.gov/JScript/metrics/
.chevron\.com/js/chevron_ga\.js
.cknw\.com[/&:?=_].*/s_cknwam_code\.js
.cleartrip\.com/javascripts/ga\..*\.js
.cya2\.net/js/STAT/
.cyanogenmod\.org/tracking\.js
.dialog\.com/js/wt\.js
.ehow\.com/px\.gif
.epson\.com/2005redesign/ww_ga\.js
.expedia\.com[/&:?=_].*/tracking\.js\?
.firstdirect\.com/.*/scripts/optimise\.js
.foodandwine\.com/javascripts/_fw_track\.js
.force\.com/resource/.*/js_hitcount
.force\.com/resource/.*/js_omniture
.fujitsu\.com/inc/wt\.js
.gizmodo\.com/api/.*/annotations
.google\.com/jsremotelog\?
.google\.com/sierralogout\?
.gotraffic\.net[/&:?=_].*/breg-min\.js
.govt\.nz/ga\.js
.hola\.org/_virt_track_activation
.hollywood\.com/toolbar_reporting\.js
.images-amazon\.com[/&:?=_].*/js/mbox\.
.imgur\.com/min/px\.js
.ioam\.de/iam\.js
.lasikplus\.com/scripts/s_code
.lendingclub\.com[/&:?=_].*/home_mbox_
.libertymutual\.com[/&:?=_].*/analytics/SC_Code\.js
.linkedin\.com/pulse/api/tracking\?
.mail\.google\.com/mail/u/0/images/c\.gif
.manta-r1\.com[/&:?=_].*/js::omniture_s_code
.medium\.com/_/stat\?
.msecnd\.net[/&:?=_].*/dcs-red-tag3-
.mtv\.ca/scripts/globalpagetrackingalternate\.js
.mulberry\.com/includes/tracking\.js
.nationaljournal\.com/js/omniture
.nationwide\.com/aq-static/scripts/js/nw_wt_fpc\.js
.neopets\.com/js/ga\.js
.nissanusa\.com/js/crm/page_tags/.*\.js
.nokia\.co\.in[/&:?=_].*/nokia_popup_script_in\.js
.nyc\.gov/html/misc/scripts/nycwebtrends\.js
.olark\.com/nrpc/.*=pollevents
.onlineshoes\.com[/&:?=_].*/s_ols_code\.
.oodle\.com/jaml/reporting/
.randomhouse\.com/js/resxclsa35\.js
.reuters\.com/pulse/2/trb\.js
.reutersmedia\.net[/&:?=_].*/rcom-parsely\.js
.reutersmedia\.net[/&:?=_].*/rcom-tracking\.js
.rogersdigitalmedia\.com/libs/analytics/RDMOmniture\.swf
.s\.update\.entrepreneur\.com[/&:?=_]
.schwab\.com[/&:?=_].*filename=hbx\.js
.seatguru\.com[/&:?=_].*/sg-tracking\.js
.servingyourtown\.com/js/metrics\.js
.shoes\.com/scripts/bvreporting\.js
.shoplocal\.com/.*/scripts/tracking\.js
.slimg\.com/js/AWD/Tracking\.nano\.js
.spotify\.com/xhr/json/log\.php
.thomasnet\.com/javascript/dcs_
.timeinc\.net/shared/static/swf/ComScoreEWCom\.swf
.toptenreviews\.com/scripts/omn_id\.php
.trademe\.co\.nz/Javascript/LoadAudienceSegs-bdl\?
.trademe\.co\.nz[/&:?=_].*/LogJavaScriptError\.ashx
.travelpn\.com/js/WRc6\.js
.treehousetv\.com/Scripts/urloverride\.js
.tribdss\.com/meter/
.ukbride\.co\.uk/js/frontend/tracker\.js
.webroot\.com/js/om_sc\.js
.wsj\.net/javascript/.*/Tracking\.js
.yimg\.com/uq/syndication/yad\.js
.yimg\.com[/&:?=_].*/g-d-min\.js
.yimg\.com[/&:?=_].*/gemini\.js
.5min\.com/flashcookie/
.5min\.com/Handlers/FiveminCookieCache\.ashx
.bunsen\.wapolabs\.com[/&:?=_]
.dsr\.livefyre\.com/livecountping/
.fwmrm\.net[/&:?=_].*/SurveyExtension\.swf
.fwmrm\.net[/&:?=_].*/VastTranslator\.swf
.googletagservices\.com/tag/js/check.*\.js
.grvcdn\.com/moth-min\.js
.ooyala\.com/3rdparty/visible_measures_
.stats\.computecmedia\.de[/&:?=_]
.tags\.tiqcdn\.com/utag/.*/utag\.v\.js
.targeting\.wpdigital\.net[/&:?=_]
.tracknet\.twyn\.com[/&:?=_]
.webcount\.finn\.no[/&:?=_]
/hit\.xiti\?
.be2\.com/tracker;
.emailretargeting\.com[/&:?=_]
.stats\.stats\.fr[/&:?=_]
.tracking\.bestofmicro\.com[/&:?=_]
.tracking\.infos-du-net\.com[/&:?=_]
.tracking\.presence-pc\.com[/&:?=_]
.tracking\.tomsguide\.fr[/&:?=_]
.veoxa\.com[/&:?=_]
.wysistat\.com[/&:?=_]
\.de/log/\?
\.de/pstat/
\.de/stat/
\.de/track/
\.tv/tracking\?
.met\.vgwort\.de/na/
.perlentaucher\.de/cgi-bin/blanky\?
.trk\.newtention\.net[/&:?=_]
/adBlockerTrack_
.cloudfront\.net/abw\.js
.reutersmedia\.net[/&:?=_].*/px\.js
.techweb\.com/adblocktrack
{ +filter{enhancedstats} }
*
{ -block }
.torontosun\.com/assets/js/paywall\.min\.js
.thepiratebay\.se[/&:?=_].*/details\.js
.thepiratebay\.se[/&:?=_].*/effects\.js
.thepiratebay\.se[/&:?=_].*/prototype\.js
.thepiratebay\.se[/&:?=_].*/scriptaculous\.js
.thepiratebay\.se[/&:?=_].*/tpb\.js
.9c9media\.com[/&:?=_].*/advertisement\.js
.buzzfed\.com[/&:?=_].*/ads\.js
.canada\.com[/&:?=_].*/advertisement\.js
.cdnslate\.com/wp-srv/ad/.*/loader\.min\.js
.doubleclick\.net/instream/ad_status\.js
.exactly0r\.com/advertising\.js
.forums\.qrz\.com/js/advertisement\.js
.motherjones\.net/adtracking\.js
.motherless\.com/scripts/site_ads\.js
.oddee\.com/js/advertising\.js
.ookla\.com/www/test\.js
.ora\.tv[/&:?=_].*/adframe\.js
.photobucket\.com[/&:?=_].*/ads\.js
.ps4news\.com/ad/adframe\.js
.techweekeurope\.co\.uk[/&:?=_].*/advertising\.js
.theatlantic\.com[/&:?=_].*/advertisement\.js
.vice\.com/assets/js/vmp/adblocker/
.vox-cdn\.com/javascripts/lib/advertisement\.
.wired\.com/ams/page-ads\.js
.aarp\.net/etc/aarp/statics/global/js/omniture.*\.js
.abcnews\.com/assets/flash/kdp/omniturePlugin\.swf
.actiris\.be/urchin\.js
.adobe\.com/uber/js/.*s_code
.adobe\.com/www\.adobe\.com/uber/js/pdc_s_code\.js
.amd\.com/.*/scode_global\.js
.apple\.com/pages/omniture/js/util\.js\?
.apple\.com[/&:?=_].*/omniture_tracking\.js
.arctichome\.com/flex-mod/js/tracking/webtrends-.*\.js
.arstechnica\.net/wp-content/themes/.*/omniture/
.arvest\.com/common/urchin/urchin\.js
.automotive\.com[/&:?=_].*/omniture/
.bankofamerica\.com/pa/components/.*/TouchClarity\.js
.bissell\.com/min\.axd\?
.bose\.com/assets/js/site_catalyst_functions\.js
.bt\.com/static/includes/homepage/touchclarity/.*/omtr_tc\.js
.canada\.com/js/global_s_code\.js
.canadiantire\.ca/content/canadian-tire/.*\.sitecatalyst\.
.canadiantire\.ca/etc/clientlibs/foundation/sitecatalyst/
.canadiantire\.ca/etc/cloudservices/.*/mbox\.js
.cartoonnetwork\.com\.au/include/omniture/s_code\.php
.cartoonnetworkasia\.com/include/omniture/s_code\.php
.cdnbrm\.com/images/.*/TouchClarity/images/
.cigna\.com[/&:?=_].*/webtrends/
.cineworld\.co\.uk/cw/assets/javascript/webtrends.*\.js
.consumerist\.com/mt\.js
.converse\.com/handler/OmnitureHandler\.ashx
.delvenetworks\.com/player/common/scripts/delve-omniture-callback\.js
.dicksmith\.co\.nz[/&:?=_].*/site-tracker\.js
.disney\.go\.com/globalelements/footer/comscore\.txt
.ea\.com/omniture/
.eircomphonebook\.ie/js/wt_capi\.js
.eonline\.com/includes/js/sitecatalyst/s_all\.jsp
.espncdn\.com/prod/scripts/mbox\.20\.r2\.js
.filmmagic\.com/scripts/tracking/omniture-communicator-basic\.js
.filmmagic\.com/scripts/tracking/omniture-page-communicator\.js
.focus\.ti\.com[/&:?=_].*/hbx\.js
.focus\.ti\.com[/&:?=_].*/hbx_page_code\.js
.foodnetwork\.ca/UserControls/.*/omnitureMedia\.swf
.foxtel\.com\.au/shop/packages-and-deals/static/js/os-omniture\.js
.google-analytics\.com/plugins/ua/ecommerce\.js
.gq\.com/js/ecomfw\.min\.js
.greenbaypressgazette\.com/odygel/lib/vendor/omniture/sitecatalyst\.js
.guardianapps\.co\.uk/jwplayer/omniture-H\.25\.2d\.js
.guim\.co\.uk/static/.*/scripts/omniture-
.healthgrades\.com/Consumer/scripts/omniture_settings\.js
.hewitt\.com[/&:?=_].*/js/analytics/
.hsbc\.co\.uk[/&:?=_].*/html/hsbcukcommon/touchclarity/
.hsn\.com/coremetrics/cmcustom\.js
.hulu\.com/site-player/.*\?referrer=
.hyundaiusa\.com/js/home/classes/HN\.Omniture\.js
.i\.imedia\.cz/javascript\?.*&referer=
.interest\.com/content/plugins/bankrate-global/javascript/bglf-s_code\.js
.interflora\.co\.uk/kernel/coremetrics/cmdatatagutils\.js
.interflora\.co\.uk/kernel/coremetrics/eluminate\.js
.jsonline\.com/templates/Proxy\.api\?
.kentucky\.com/mistats/products/pubsys_s_code\.js
.marilyn\.ca/jsHandler\.aspx\?.*omniture
.mfcreative\.com[/&:?=_].*/mbox\.js
.microsoft\.com/Areas/Global/Content/Omniture/
.microsoft\.com/Combined\.js\?.*/Omniture/
.microsofttranslator\.com[/&:?=_].*/SiteCatalyst\.js
.miniusa\.com/js/dcs_tag\.js
.mlb\.mlb\.com/shared/flash/tracking/bamnet_omniture_as3\.swf
.mnginteractive\.com/live/js/omniture/OmnitureHelper\.js
.mnginteractive\.com/live/js/omniture/SiteCatalystCode_.*\.js
.mnginteractive\.com/live/omniture/sccore\.js
.mycoke\.com/js/tracking\.js
.mycokerewards\.com/flex-mod/js/tracking/webtrends-
.mycricket\.com/js/hbx\.js
.myrecipes\.com/static/j/ext/omniture/
.n-tv\.de/stat/videoplayer/
.nationalgeographic\.com/stats/omniture_code\.js
.nationalgeographic\.com/wpf/sites/common/j/omniture_code\.js
.nationaljournal\.com/js/libs/omniture/core\.js
.nba\.com/tvc/script/tvc_omniture_code\.js
.nbcphiladelphia\.com/includes/customOmnitureData\.js
.nedvang\.nl/sites/all/.*/PageView\.js
.newegg\.com/WebResource/Scripts/.*eluminate\.en\.js
.news\.sky\.com/sky-news/app/.*/swf/OmniturePlugin\.swf
.newsday\.com/build/nd_omniture\.min\.js
.newsday\.com/js/s_nd_code\.js
.nfl\.com/yui/min2/index\.php\?.*nfl-omniture\.js
.nflcdn\.com/static/site/.*-omniture\.js
.nflcdn\.com/yui/min2/index\.php\?.*-omniture\.js
.nintendo\.com/js/omniture-prod\.js
.nytimes\.com/bi/js/analytics/nyt4/controller\.js
.nzherald\.co\.nz/themes/.*/s_code\.min\.js
.o\.aolcdn\.com[/&:?=_].*&file=/aol/omniture\.min\.js
.optimum\.net/js/omniture/external\.js
.payback\.de/script/s_code-.*\.js
.paypalobjects\.com[/&:?=_].*/site_catalyst/
.pcworld\.com/script/omniture/video\.js
.pepsico\.com/scripts/urchin\.js
.pioneercu\.org/includes/lib/js/coremetrics/eluminate\.js
.player\.qbrick\.com[/&:?=_].*/sitecatalyst\.swf
.playserver1\.com/SiteScript/Play/.*/webtrends2\.min\.js
.pricegrabber\.com/js/combine\.js\.php\?.*=s_code_h\.
.pricegrabber\.com/js/combine\.js\.php\?.*_js_code\.
.quill\.com/js/Omniture/quill_s_code\.js\?
.rentals\.com/assets/.*webtrends-
.rentals\.com/javascripts/primedia-webtrends-
.rentals\.com/javascripts/webtrends-bindings\.js
.rightnow\.com/javascript/omniture_variable_
.rosettastone\.co\.uk[/&:?=_].*/mbox\.js
.s\.xe\.com/.*/js/webtrends\.1\.js
.sears\.com/etc/clientlibs/foundation/sitecatalyst/sitecatalyst\.min\.js
.seeingwithsound\.com/ga\.js
.simyo\.de[/&:?=_].*/simyo_s_code\.js
.sixflags\.com/global/func/js/siteCatalyst\.js
.sky\.com/flash-video-player-.*/OmniturePlugin\.swf
.space\.ca/jsHandler\.aspx\?src=.*\.omniture\.js
.startribune\.com/includes/Omniture\.H\.24\.js
.storage\.ie6countdown\.com/assets/.*/ie6ct_s_code\.js
.subscription-assets\.ew\.com/prod/assets/.*/omniture/
.subscription-assets\.timeinc\.com/prod/assets/.*/omniture/
.surfline\.com/functions/page_tracker\.cfm
.swfs\.bimvid\.com/omniture-.*\.swf
.symantec\.com/script/omniture/om_code\.js
.tampabay\.com/universal/scripts/omniture/tb_code\.js
.thecomedynetwork\.ca/jsHandler\.ashx
.thepiratebay\.se[/&:?=_].*/jquery\.min\.js
.thestar\.com[/&:?=_].*/sitecatalyst/
.ticketmaster\.com[/&:?=_].*/omniture_tracker\.js
.topmarques\.co\.uk[/&:?=_].*/tracking/module\.omniture\.js
.traderonline\.com/javascript/master_s_code\.js
.tvlistings\.optimum\.net/foresee/foresee-trigger\.js
.unionbank\.com/coremetrics/.*/eluminate\.js
.unionbank\.com/coremetrics/cmdatatagutils\.js
.ups\.com/javascript/webtrends.*\.js
.usairways\.com/en-US/Resources/javascript/omniture.*\.js
.verizon\.com/content/contactus/includes/javascript/hbx\.js
.victoriassecret\.com/app/coremetrics/eluminate\.js
.video\.nbcuni\.com/core/.*/omniture_
.videos\.mediaite\.com/embed/.*\?referrer=http
.washingtonpost\.com/wpost/js/combo\?token.*/wp_omniture\.js
.weather\.com/clients/widgets/.*\?referrer=http
.wired\.com/js/omniture/omniture_helpers\.js
.wireimage\.com/scripts/tracking/omniture-communicator-basic\.js
.wireimage\.com/scripts/tracking/omniture-page-communicator\.js
{ -block +handle-as-image }
/omniture\.js
/s_code\.
.google-analytics\.com/ga\.js
